flowchart LR

    SensorTask[SensorTask] -->|latest sample| xDisplayQueue[xDisplayQueue]

    xDisplayQueue --> xDisplayEvents[xDisplayEvents]

    InputTask[InputTask] -->|selected mode| xModeQueue[xModeQueue]

    xModeQueue --> xDisplayEvents

    xDisplayEvents --> DisplayTask[DisplayTask]

    SensorTask -->|latest sample| xAlarmQueue[xAlarmQueue]

    xAlarmQueue --> AlarmTask[AlarmTask]

    MotionTask[MotionTask] -->|MOTION event| xSystemEvents[xSystemEvents]

    StateTask[StateTask] -->|ACTIVE event| xSystemEvents

    AlarmTask -->|ALARM event| xSystemEvents

    DisplayTask --> OLED[SSD1306 OLED]

    SensorTask --> serialMutex[serialMutex]
    InputTask --> serialMutex
    MotionTask --> serialMutex
    StateTask --> serialMutex
    AlarmTask --> serialMutex
    DisplayTask --> serialMutex

    serialMutex --> USART1[USART1 Serial]